# -*- coding: utf-8 -*-
"""Descuento Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W_dT1Xb20n1FJfHGcrE1VRAYn9_78siJ
"""

Ferrari = 5000
Descuento = Ferrari *15/100
Descuento_Ferrari = Ferrari - Descuento
print(Descuento_Ferrari)