# -*- coding: utf-8 -*-
"""Operaciones python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/157-F-3NWdPdhqm11djtCf7mjdsz2kfqW
"""

a = 15
b = 1
c = a + b
print(c)

a = 15
b = 1
c = a - b
print(c)

a = 15
b = 1
c = a * b
print (c)

a = 15
b = 1
c = a / b
print(c)

a = 15
b = 1
c = a % b
print(c)