# -*- coding: utf-8 -*-
"""Variables Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EFZDb7s6yjURIBZSeeVc-Tvwpq-ThYdh
"""

a = 10
b = 5
c = 3
d = 2
e = 4
x = ((a + b - c)*d)/e
print(x)